default: &default
  adapter: postgresql 
  encoding: unicode

development:
  <<: *default
  database: moar-coffee_development
test:
  <<: *default
  database: moar-coffee_test

production:
  <<: *default
  database: moar-coffee_production